import './globals.css'
import Footer from '../components/footer'

export const metadata = {
	title: 'Google clone',
	description: 'Generated by Farrux Ganiboyev',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='relative min-h-screen'>
				<Footer />
				{children}
			</body>
		</html>
	)
}
